[package]
cairo-version = "2.1.1"
name = "zknight"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", tag = "cairo-v2.1.0" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.2.1" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x3ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x300001800000000300000180000000000030000000000003006001800006600"
world_address = "0x414a30414c283c7023452c9d51e8cd11532260f6a65f9920d91feaed8750d39"

# Madara testnet
# rpc_url = "https://api.cartridge.gg/x/shinai/madara"
# account_address = "0x2"
# private_key = "0xc1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d"
